server:
  mysql_source: "root@localhost/tiktok"
  port: 25010
  host: "localhost:25010"
  redis:
    addr: "localhost:6379"
    password: ""

auth:
  # define the secret key
  jwt_key: ""


video:
  # left it empty to get from path
  ffmpeg: ""