server:
  mysql_source: "root@localhost/tiktok?parseTime=true&loc=Local"
  port: 25010
  host: "localhost:25010"
  redis:
    addr: "localhost:6379"
    password: ""

auth:
  # define the secret key
  jwt_key: ""

# tencent cloud cos
bucket:
  url: ""
  secret:
    id: ""
    key: ""
